s = set()
n = input("Enter num 1 : ")
s.add(int(n))
n = input("Enter num 2 : ")
s.add(int(n))
n = input("Enter num 3 : ")
s.add(int(n))
n = input("Enter num 4 : ")
s.add(int(n))
n = input("Enter num 5 : ")
s.add(int(n))
n = input("Enter num 6 : ")
s.add(int(n))
n = input("Enter num 7 : ")
s.add(int(n))
n = input("Enter num 8 : ")
s.add(int(n))

print(s)